-- CREATE DATABASE doowell;
USE doowell;

DROP TABLE IF EXISTS `habits`;
CREATE TABLE `habits` (
  `id` INTEGER AUTO_INCREMENT NOT NULL,
  `habit` VARCHAR(1000) NOT NULL,
  `date` DATE NOT NULL,
  `hex_color` VARCHAR(6) DEFAULT 'f7d088',
  PRIMARY KEY (`id`)
);


DROP TABLE IF EXISTS `tracked-habits`;
CREATE TABLE `tracked-habits` (
  `id` INTEGER AUTO_INCREMENT NOT NULL,
  `habit` VARCHAR(500) UNIQUE NOT NULL,
  PRIMARY KEY (`id`)
);


DROP TABLE IF EXISTS `tasks`;
CREATE TABLE `tasks` (
  `id` INTEGER AUTO_INCREMENT NOT NULL,
  `task` VARCHAR(1000) NOT NULL,
  `category` VARCHAR(200) NOT NULL,
  `completed` INTEGER NOT NULL DEFAULT 0,
  `hex_color` VARCHAR(6) DEFAULT 'f7d088',
  PRIMARY KEY (`id`)
);


DROP TABLE IF EXISTS `reminders`;

CREATE TABLE `reminders` (
  `id` INTEGER AUTO_INCREMENT NOT NULL,
  `reminder` VARCHAR(2000) NOT NULL,
  `completed` INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`)
);

